#!/usr/bin/env bash
# Build the in-browser client-side-prediction module: the SAME carved C as
# sim_oracle, compiled freestanding to WebAssembly (clang --target=wasm32), with the
# trig table baked from `sim_oracle --dump-trig` (identical to the chain's Trig.sol,
# so no libm sin() and no risk of a 1-ULP divergence), then optimized with binaryen.
#
# Needs: clang with the wasm32 backend + wasm-ld (LLVM), and wasm-opt (binaryen).
# No Emscripten / wasi-sdk required. Output (gitignored, like contracts/out):
#   web/public/predict.wasm
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=oracle/src
BUILD=oracle/build
OUT=web/public/predict.wasm
mkdir -p "$BUILD" "$(dirname "$OUT")"

# 1. native oracle — only to dump the trig table
make -C oracle >/dev/null

# 2. bake the trig table (the same 450 uint32 that Trig.sol uses) into a C header,
#    so the wasm build needs no libm sin() and matches the chain bit-for-bit.
oracle/build/sim_oracle --dump-trig | fold -w8 | awk '
    BEGIN { print "/* generated by oracle/build_wasm.sh from `sim_oracle --dump-trig` */";
            print "#include <stdint.h>";
            print "static const uint32_t BAKED_SINTABLE[] = {" }
          { printf "    0x%s,\n", $0 }
    END   { print "};" }' > "$BUILD/trigtable.h"

# 3. compile the sim to a freestanding wasm reactor. -fvisibility=hidden + the
#    EXPORT attribute export ONLY the prediction API; --gc-sections drops the unused
#    BuildTables() (its sin() is the only libm reference); -mbulk-memory lowers struct
#    copies to memory.copy/fill instead of libc calls.
clang --target=wasm32 -O2 -ffreestanding -nostdlib -mbulk-memory -fvisibility=hidden \
    -Wl,--no-entry -Wl,--export-dynamic -Wl,--gc-sections \
    -Wl,--export=__heap_base -Wl,-z,stack-size=262144 \
    -I oracle/wasm_include -I"$SRC" -I"$BUILD" \
    "$SRC/wl_sim.c" "$SRC/wl_actor.c" "$SRC/wl_rng.c" "$SRC/wl_wasm.c" \
    -o "$BUILD/predict.raw.wasm"

# 4. optimize + shrink with binaryen
wasm-opt -O3 --enable-bulk-memory "$BUILD/predict.raw.wasm" -o "$OUT"

echo "built $OUT ($(wc -c < "$OUT") bytes)"
